---
swagger: "2.0"
info:
  description: "This is the API specification for the [Crops in Silico](http://cropsinsilico.org/)\
    \ project.  This documentation was generated by [Swagger](http://swagger.io)."
  version: "1.0.0"
  title: "Crops in Silico API"
  termsOfService: "https://www.wikihow.com/Write-Terms-and-Conditions"
  contact:
    email: "lambert8@illinois.edu"
  license:
    name: "License Unknown"
    url: "https://choosealicense.com/"
host: "cis.mldev.ndslabs.org"
basePath: "/api/v1"
tags:
- name: "simulations"
  description: "Operations around simulations"
  externalDocs:
    description: "Find out more"
    url: "https://cropsinsilico.github.io/cis_interface/"
schemes:
- "https"
paths:
  /models:
    get:
      tags:
      - "links"
      summary: "Retrieve a list of all available models in the system"
      description: ""
      operationId: "get_models"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Model"
      x-swagger-router-controller: "swagger_server.controllers.links_controller"
  /nodes:
    get:
      tags:
      - "nodes"
      summary: "Retrieve a list of nodes representing instances of the models of the\
        \ system"
      description: ""
      operationId: "get_nodes"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Node"
      x-swagger-router-controller: "swagger_server.controllers.nodes_controller"
  /links:
    get:
      tags:
      - "models"
      summary: "Retrieve a list of links between the nodes of the system"
      description: ""
      operationId: "get_links"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Link"
      x-swagger-router-controller: "swagger_server.controllers.models_controller"
  /simulations:
    get:
      tags:
      - "simulations"
      summary: "Retrieve a list of all prior simulations"
      description: ""
      operationId: "get_simulations"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Simulation"
      x-swagger-router-controller: "swagger_server.controllers.simulations_controller"
    post:
      tags:
      - "simulations"
      summary: "Create a new simulation"
      description: ""
      operationId: "post_simulations"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "A new set of simulation models to run"
        required: true
        schema:
          $ref: "#/definitions/Simulation"
      responses:
        200:
          description: "OK"
        400:
          description: "Invalid input"
        500:
          description: "Server error"
      x-swagger-router-controller: "swagger_server.controllers.simulations_controller"
definitions:
  Model:
    type: "object"
    properties:
      name:
        type: "string"
        description: "The short name / identifier of this model"
      path:
        type: "string"
        description: "Path to the YAML file on disk representing this model"
    example:
      name: "name"
      path: "path"
  Node:
    type: "object"
    properties:
      name:
        type: "string"
      model:
        $ref: "#/definitions/Model"
    example:
      model:
        name: "name"
        path: "path"
      name: "name"
      links:
      - to: null
        weight: 0
        name: "name"
        from: null
      - to: null
        weight: 0
        name: "name"
        from: null
  Link:
    type: "object"
    properties:
      name:
        type: "string"
      from:
        $ref: "#/definitions/Node"
      to:
        $ref: "#/definitions/Node"
      weight:
        type: "integer"
    example:
      to: null
      weight: 0
      name: "name"
      from: null
  Simulation:
    type: "object"
    properties:
      models:
        type: "array"
        items:
          $ref: "#/definitions/Model"
      namespace:
        type: "string"
    example:
      models:
      - name: "name"
        path: "path"
      - name: "name"
        path: "path"
      namespace: "namespace"
externalDocs:
  description: "Find out more about Crops in Silico"
  url: "http://cropsinsilico.org/about-us/"
